services: 
  mysqlDB:
    hostname: mysqlDB
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ka014626
      MYSQL_DATABASE: DB_Service
      MYSQL_USER: SimpleAppUserID
      MYSQL_PASSWORD: LearnTogrow123!
  simple_spring_Api:
    hostname: SpringApiApp
    image: simple_spring_api
    environment:
      DB_URL: jdbc:mysql://mysqlDB:3306/DB_Service
      DB_USERNAME: SimpleAppUserID
      DB_PASSWORD: LearnTogrow123!
    depends_on:
     - mysqlDB 