services: 
  mysqlDB:
    hostname: mysqlDB
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ka014626
      MYSQL_DATABASE: DB_Service
      MYSQL_USER: SimpleAppUserID
      MYSQL_PASSWORD: LearnTogrow123!
 