services: 
  mysqlDB:
    hostname: mysqlDB
    container_name: mysqlDB
    image: mysql
    
    
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ka014626
      MYSQL_DATABASE: DB_Service
      MYSQL_USER: SimpleAppUserID
      MYSQL_PASSWORD: LearnTogrow123!
  simple_spring_Api1:
    hostname: SpringApiApp1
    container_name: SpringApiApp1
    image: simple_spring_api
    ports:
      - 8081:8080
    environment:
      DB_URL: jdbc:mysql://mysqlDB:3306/DB_Service
      DB_USERNAME: SimpleAppUserID
      DB_PASSWORD: LearnTogrow123!
    depends_on:
     - mysqlDB 
  simple_spring_Api2:
    hostname: SpringApiApp2
    container_name: SpringApiApp2
    image: simple_spring_api
    ports:
      - 8082:8080
    environment:
      DB_URL: jdbc:mysql://mysqlDB:3306/DB_Service
      DB_USERNAME: SimpleAppUserID
      DB_PASSWORD: LearnTogrow123!
    depends_on:
     - simple_spring_Api1 
  nginx:
    build:
      context: .
      dockerfile: "./DockerBuilds/DockerFile_nginx"
    container_name: nginxLoadBalancer

    ports:
      - "801:80"
    depends_on:
      - simple_spring_Api1
      - simple_spring_Api2


  