# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file to the container
COPY ./simple_spring_api/target/spring-boot-mysql-1.0.0.jar application.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "application.jar"]
