# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file to the container
COPY demo-0.0.1-SNAPSHOT.jar  application.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "application.jar"]
